### ISSUE TITLE
Events are somewhat misplaced if min/max prop is used with odd number of hours

### ISSUE THREAD

**Issue by marwej** [intljusticemission/react-big-calendar#749]
#### What's the current behavior?

If `min` and `max` prop is used with vales that result in odd number of hours, the actual viewable area is extended to an even number of hours. This makes the layout algorithm calculate wrong position for events.

https://codesandbox.io/s/91mwr9q53w

**Comment by Iancam** [comment]
Appears that this has been solved for odd numbers of hours in v.19, but the same thing happens when you specify a minute offset for the start or end times.

**Comment by marlonmantilla** [comment]
Hi guys, i'm still seeing this issue when using max the timeslots are being moved slightly down. If i use only min it works fine, but as soon as max is added is breaking it. 

Currently on v0.20.1.

Would appreciate if there's any clue about this.

**Comment by PeterYangIO** [comment]
@marlonmantilla I came across #999 and it looks like subtracting 1 minute from the max makes it work

**Comment by marlonmantilla** [comment]
@PeterYangIO thanks that worked!
